config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
profiles:
  waldbiec-Latitude-7490:
    dotfiles:
    - f_vimrc
