config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    chmod: '644'
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_bash_prompt:
    src: bash_prompt
    dst: ~/.bash_prompt
  f_postactivate:
    src: virtualenvs/postactivate
    dst: ~/.virtualenvs/postactivate
  f_postdeactivate:
    src: virtualenvs/postdeactivate
    dst: ~/.virtualenvs/postdeactivate
  f_git-commit-template:
    src: git-commit-template
    dst: ~/.git-commit-template
  f_rc.conf:
    src: config/ranger/rc.conf
    dst: ~/.config/ranger/rc.conf
profiles:
  work:
    dotfiles:
    - f_vimrc
    - f_bashrc
    - f_gitconfig
    - f_bash_prompt
    - f_postactivate
    - f_postdeactivate
