-- ==================
-- Lua configurations
-- ==================

require('user.vimplug')
require('user.nvim-webdev-icons')
require('user.mini-icons')
require('user.snacks')
require('user.neoformat')
require('user.options')
require('user.behaviors')
require('user.keymaps')
require('user.colorschemes')
require('user.node_modules_util')
require('user.lsp')
require('user.completer')
require('user.null-ls-cfg')
require('user.gitsigns')
require('user.syntax')
require('user.lualine')
require('user.whichkey')
require('user.toggleterm')
require('user.undotree')
require('user.pysql')
require('user.refjump')
require('user.screenkey')
require('user.keepcursor')
